# Generated by Django 3.1.7 on 2021-05-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendships',
            options={'verbose_name_plural': 'Friendships'},
        ),
    ]
