# Generated by Django 3.1.7 on 2021-03-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0002_auto_20210315_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
    ]
