# Generated by Django 3.1.7 on 2021-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0002_auto_20210507_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshiprequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
