# Generated by Django 3.1.7 on 2021-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0003_friendshiprequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='perfectbalance',
            name='perfect_body',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='perfectbalance',
            name='perfect_mind',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='perfectbalance',
            name='perfect_soul',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profilebio',
            name='biography',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='profiledisplayname',
            name='display_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepost',
            name='headline',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='profilequote',
            name='quote',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='profilequote',
            name='quote_author',
            field=models.CharField(max_length=30),
        ),
    ]
