# Generated by Django 3.1.7 on 2021-06-20 19:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0006_auto_20210616_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
