# Generated by Django 3.1.7 on 2021-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0007_profiletimezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletimezone',
            old_name='timezone',
            new_name='user_timezone',
        ),
    ]
