# Generated by Django 3.1.7 on 2021-04-29 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0009_balancestreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancestreak',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
