# Generated by Django 3.1.7 on 2021-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0012_auto_20210624_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportreport',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
