# Generated by Django 3.1.7 on 2021-05-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro_app', '0016_pinnedprofilepost_date_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedprofilepost',
            old_name='date_pinned',
            new_name='date_published',
        ),
    ]
