# Generated by Django 3.1.7 on 2021-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Friendship Request'), (2, 'Accepted Friendship Request'), (3, 'Pinned Post')], default=1),
            preserve_default=False,
        ),
    ]
