# Generated by Django 3.1.7 on 2021-05-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Friendship Request'), (2, 'Accepted Friendship Request'), (3, 'Pinned Post'), (4, 'New Post')]),
        ),
    ]
